USE [master]
GO

CREATE DATABASE [DB_BERNHOEFT]
GO

USE [DB_BERNHOEFT]
GO

CREATE TABLE TBLCATEGORIA(
	IDCATEGORIA INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	SITUACAO VARCHAR(7) NOT NULL
)

CREATE TABLE TBLPRODUTO(
	IDPRODUTO INT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL,
	PRECO FLOAT NOT NULL,
	SITUACAO VARCHAR(7) NOT NULL,
	IDCATEGORIA INT NOT NULL,
	CONSTRAINT PK_PRODUTO PRIMARY KEY(IDPRODUTO),
	CONSTRAINT FK_CATEGORIA_PRODUTO FOREIGN KEY(IDCATEGORIA) REFERENCES TBLCATEGORIA(IDCATEGORIA)
)